### ISSUE TITLE
Tried to register two views with the same name rnsvgpath

### ISSUE THREAD

**Issue by RyanGostosaum** [creativetimofficial/material-kit-react-native#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

App should run

# Current Behavior

Error: "tried to register two views with the same name rnsvgpath"

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. git clone
2. npm install
3. npm start

## Context

- Last version of Material-kit-react-native
- Node: 10.15.0
- Expo: ^31.0.2

* Device: Samsung J7 Neo (phisical device)
* Operating System: W10
* Browser and Version: Chrome 71.0.3578.98 x64

**Comment by JaewonKim** [comment]
I have the same issue too.

**Comment by ianeinser** [comment]
+1

**Comment by devingray** [comment]
+1

**Comment by palingheorghe** [comment]
Hi @RyanGostosaum, @ianeinser, @devingray, @JaewonKim,

Thank you for trying out our products! I'm sorry for all the issues you encountered but everything is supposed to work now. Download a new instance of our project, use `npm install` in order to install all the necessary dependencies and you're ready to go! 

Thank you for your patience! 
Best wishes, 
Alin
