### ISSUE TITLE
switching tabs with left/right swipe

### ISSUE THREAD

**Issue by AndreasEK** [creativetimofficial/material-kit-react-native#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
Support for gesture control in navigation, especially switching tabs in Galio Framework's NavBar component with left/right swipe

# Current Behavior

What is the current behavior?
No gesture control is supported, although a dependency to react-native-gesture-handler exists, it's not used.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by palingheorghe** [comment]
Hi @AndreasEK ! Thank you for being interested in our products! Sorry for the late reply. I think this is a good idea, we could implement something like that in our apps. The `react-native-gesture-handler` was a must have dependency because of Expo. So it has nothing to do with the idea of having these gestures implemented. We'll probably implement this feature in our next version. 

Thanks, 
Alin!
