### ISSUE TITLE
Duplicate resources for ttf files

### ISSUE THREAD

**Issue by bcteam2020** [creativetimofficial/material-kit-react-native#31]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

eas build:android should work like expo build:android

# Current Behavior
duplicate resources error is being thrown

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

Run the below command
eas build:android 

## Context
It is working fine with expo build:android
the problem is occuring with eas build:android

## Failure Logs
[raw/assets_fonts_galioextra] /private/var/folders/k9/ht821f996yq6048p9tr5bz8m0000gn/T/eas-build-local-nodejs/ddb6ac6a-c728-46af-a2e4-4e025f695ee4/build/android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.ttf        [raw/assets_fonts_galioextra] /private/var/folders/k9/ht821f996yq6048p9tr5bz8m0000gn/T/eas-build-local-nodejs/ddb6ac6a-c728-46af-a2e4-4e025f695ee4/build/android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.json: Error: Duplicate resources

**Comment by hetmann** [comment]
@bcteam2020 thank you for noticing this error/issue.
- The main reason for this is how the resources are bundled & cached, usually this can be fixed by removing the `raw folder`
- Another issue it can be due to how the resources are linked (aka `react-native link`), they are copied into raw folder and each time a build is trigger it tries to copy the same resource and the "Duplicate sources" error is triggered.

Solution:
Try to delete the raw folder from `android/app/build/generated/res/react/release/raw/` or from your `local android raw folder`

**Comment by bcteam2020** [comment]
we have resolved this

Solution:
under assets/fonts there are two files with same name but different extension
galioExtra.json
galioExtra.ttf
rename either of the them like galioExtra.ttf --->galioExtra**1**.ttf
Android is throwing errors for files with same name but different extension
