### ISSUE TITLE
Is it possible to exclude Expo?

### ISSUE THREAD

**Issue by ianeinser** [creativetimofficial/material-kit-react-native#8]
Hello,

I would like to know if there is any version without Expo libraries? or is it possible to use it without Expo?

**Comment by palingheorghe** [comment]
Hi @ianeinser, 
Unfortunately, there isn't any version without Expo at the moment. You could always try to eject Expo from the project and do all the necessary steps in order to remove it completely. You can find more information regarding this [here](https://docs.expo.io/versions/latest/expokit/eject/).

Thanks,
Alin 🧜🏽‍♂️
